# src/engines/sql_validator.py
# Module 3 — SQL Safety Validator
#
# One function: validate_sql(query) → bool
# Returns True if the query is safe to execute, False if it's dangerous.
#
# Security principle: allowlist approach.
# We don't try to enumerate every dangerous thing — we only allow SELECT.
# Anything that is not a SELECT query is blocked.

# These keywords indicate data-modifying or schema-modifying SQL.
# If ANY of these appear in the query, it is rejected immediately.
FORBIDDEN_KEYWORDS = [
    "DROP",
    "DELETE",
    "INSERT",
    "UPDATE",
    "ALTER",
    "CREATE",
    "TRUNCATE",
    "EXEC",
    "EXECUTE",
    "PRAGMA",      # SQLite-specific: can modify database settings
    "--",          # SQL comment — can be used to hide malicious clauses
    ";",           # Statement terminator — prevents SQL injection chaining
]


def validate_sql(query: str) -> bool:
    """
    Check whether a SQL query is safe to execute against the database.

    Strategy: uppercase the entire query, then scan for forbidden keywords.
    If any forbidden keyword is found → return False (block it).
    If the query doesn't start with SELECT → return False (block it).
    Otherwise → return True (allow it).

    Args:
        query: The SQL string generated by the LLM.

    Returns:
        True  → query is safe, proceed to execution
        False → query is dangerous or malformed, do not execute
    """
    if not query or not query.strip():
        return False

    # Uppercase for case-insensitive matching
    # Groq might return 'select' or 'SELECT' or 'Select' — treat them all the same
    upper_query = query.upper().strip()

    # Rule 1: Must start with SELECT
    # This is the primary guard — all read-only queries start with SELECT
    if not upper_query.startswith("SELECT"):
        return False

    # Rule 2: Must not contain any forbidden keyword
    # We check the full query, not just the first word,
    # because injected clauses can appear anywhere: SELECT * FROM data; DROP TABLE data
    for keyword in FORBIDDEN_KEYWORDS:
        if keyword in upper_query:
            return False

    return True


def get_validation_error(query: str) -> str:
    """
    Return a human-readable error message explaining why validation failed.
    Used by sql_engine.py to build a clear error response.

    Args:
        query: The SQL string that failed validation.

    Returns:
        A string describing the problem. Never shown raw to the user —
        sql_engine.py wraps it in a user-friendly message.
    """
    if not query or not query.strip():
        return "Generated query was empty"

    upper_query = query.upper().strip()

    if not upper_query.startswith("SELECT"):
        return f"Query must start with SELECT, got: {query[:50]}"

    for keyword in FORBIDDEN_KEYWORDS:
        if keyword in upper_query:
            return f"Forbidden keyword detected: {keyword}"

    return "Unknown validation failure"