# src/graph/state.py
"""
LangGraph State Definition for FinanceGPT.

This TypedDict is the single shared data object that flows through the entire
LangGraph pipeline. Every node (router, sql_node, stats_node, explain_node)
reads from and writes to this state object.

CRITICAL RULE: Only serializable types allowed.
  ✅ str, int, float, bool, list, dict, None
  ❌ pandas.DataFrame  — store file_path instead, reconstruct inside node
  ❌ SQLite connection  — store db_path instead, reconnect inside node
  ❌ Plotly Figure      — store chart_json (string) instead
  ❌ LLM objects        — never store, always create fresh via get_llm()

Why TypedDict?
  LangGraph needs to checkpoint (save/restore) state between nodes.
  TypedDict gives a strict schema so serialization always works.
  Callers always know exactly what keys exist — no KeyError surprises.
"""

from typing import TypedDict, Optional, Any


class FinanceGPTState(TypedDict):
    """
    Complete state object for one FinanceGPT query session.
    
    Lifecycle:
      1. Gradio UI populates: file_path, db_path, query, session_id
      2. Router node adds:    query_type ("sql" or "stats")
      3. SQL or Stats node adds: sql_query/stats_code + raw_result
      4. Explain node adds:   explanation
      5. Gradio UI reads:     explanation + raw_result + sql_query/stats_code
    """

    # ------------------------------------------------------------------
    # INPUT — set by the caller (Gradio UI or test harness) before graph runs
    # ------------------------------------------------------------------
    file_path: str
    # Absolute path to the user's uploaded CSV or Excel file.
    # Used by the stats node to reload the DataFrame inside its sandbox.
    # Example: "G:/Projects/finance_gpt/data/sample_sales.csv"

    db_path: str
    # Absolute path to the SQLite database file created by M1 loader.
    # Used by the SQL node to connect and execute queries.
    # Example: "G:/Projects/finance_gpt/finance.db"

    query: str
    # The user's raw natural language question.
    # Example: "What is the total sales amount by region?"

    session_id: str
    # Unique identifier for this conversation session.
    # Used by the LangGraph SQLite checkpointer (M9) to persist history.
    # Example: "session_abc123"

    # ------------------------------------------------------------------
    # ROUTING — set by M5 router node
    # ------------------------------------------------------------------
    query_type: str
    # Classification result: either "sql" or "stats"
    # "sql"   → aggregation, filter, sort, group, count, sum, top-N
    # "stats" → forecast, trend, correlation, anomaly, moving average
    # Set by: classify_query() in router.py
    # Read by: LangGraph conditional edge to decide next node

    # ------------------------------------------------------------------
    # SQL PATH — set by M3 SQL node (only populated on sql path)
    # ------------------------------------------------------------------
    sql_query: Optional[str]
    # The SQL query generated by the LLM and validated by sql_validator.
    # None if this was a stats query.
    # Shown in the Gradio UI for transparency ("Here's the SQL I ran").
    # Example: "SELECT region, SUM(total_sales) FROM data GROUP BY region"

    sql_valid: bool
    # Whether the generated SQL passed the whitelist validator.
    # False means the SQL was blocked (DROP/DELETE/etc. detected).

    # ------------------------------------------------------------------
    # STATS PATH — set by M4 stats node (only populated on stats path)
    # ------------------------------------------------------------------
    stats_code: Optional[str]
    # The Python code generated by the LLM and run in RestrictedPython.
    # None if this was a SQL query.
    # Shown in the Gradio UI for transparency.
    # Example: "result = df['total_sales'].rolling(3).mean().tolist()"

    # ------------------------------------------------------------------
    # RESULTS — set by whichever engine ran
    # ------------------------------------------------------------------
    raw_result: Optional[Any]
    # The actual data result from SQL or stats execution.
    # SQL path:   string from db.run() e.g. "[('North', 955.0), ...]"
    # Stats path: normalized Python value (list, dict, float, etc.)
    # Displayed as a raw table in the Gradio UI.

    explanation: str
    # Plain English explanation of the result, generated by Groq Mixtral.
    # This is the main answer shown to the user at the top of the UI.
    # Example: "The North region had the highest sales at $955, followed by..."

    # ------------------------------------------------------------------
    # META — error handling and caching
    # ------------------------------------------------------------------
    error: Optional[str]
    # If any node fails, it writes its error message here and the pipeline
    # short-circuits gracefully. Never shows raw stack traces to the user.
    # None when everything succeeded.

    cached: bool
    # True if this result was served from LangChain InMemoryCache (M7).
    # False for fresh computation.
    # Used by Gradio UI to show a small "⚡ Cached" badge.