# src/security/restricted_exec.py
"""
RestrictedPython sandbox for safe execution of LLM-generated stats code.

Why this exists:
- M4 Stats Engine asks the LLM to generate Pandas/NumPy Python code
- We cannot run arbitrary LLM-generated code with plain exec() — too dangerous
- RestrictedPython compiles code into restricted bytecode that blocks:
  - os, sys, subprocess (filesystem + system access)
  - open(), file I/O (can't read/write arbitrary files)
  - eval(), exec() (no code injection inside code)
  - __import__ (can't import dangerous modules)
- Only allowed: pandas, numpy, scipy, math, datetime operations

SQL path does NOT need this — SQLite SELECT-only whitelist is sufficient.
Stats path DOES need this — LLM generates executable Python.
"""

import logging
from typing import Any

from RestrictedPython import compile_restricted, safe_globals
from RestrictedPython.Guards import (
    safe_builtins,
    guarded_iter_unpack_sequence,
    guarded_unpack_sequence,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Allowed globals — what the sandboxed code can "see"
# ---------------------------------------------------------------------------
# We build a restricted globals dict. The LLM-generated code runs inside
# this scope. It can only use what's in this dict.

def _build_restricted_globals(df, np, pd, scipy_stats=None):
    """
    Build the globals dict that the sandboxed code executes within.
    
    Args:
        df: The Pandas DataFrame (the user's uploaded data)
        np: numpy module
        pd: pandas module
        scipy_stats: scipy.stats module (optional, for linregress)
    
    Returns:
        dict — the restricted execution environment
    """
    import math
    import datetime

    restricted_globals = safe_globals.copy()
    restricted_globals['__builtins__'] = safe_builtins.copy()
    
    # Inject allowed data science tools
    restricted_globals['df'] = df          # The user's data — always named 'df'
    restricted_globals['pd'] = pd          # Pandas
    restricted_globals['np'] = np          # NumPy
    restricted_globals['math'] = math      # Standard math
    restricted_globals['datetime'] = datetime  # Date handling

    # RestrictedPython guards — required for pandas/numpy operations
    restricted_globals['_getiter_']    = iter
    restricted_globals['_getattr_']    = getattr
    restricted_globals['_getitem_']    = lambda obj, key: obj[key]
    restricted_globals['_write_']      = lambda obj: obj        # allows df['col'] = ...
    restricted_globals['_inplacevar_'] = lambda op, x, y: eval(f'x {op} y', {'x': x, 'y': y})
    
    # Inject scipy if available (needed for linear regression forecasting)
    if scipy_stats is not None:
        restricted_globals['scipy_stats'] = scipy_stats
    
    # Required by RestrictedPython internals for sequence unpacking
    restricted_globals['_getiter_'] = iter
    restricted_globals['_getattr_'] = getattr
    restricted_globals['_getitem_'] = lambda obj, key: obj[key]
    restricted_globals['_iter_unpack_sequence_'] = guarded_iter_unpack_sequence
    restricted_globals['_unpack_sequence_'] = guarded_unpack_sequence
    
    return restricted_globals


# ---------------------------------------------------------------------------
# Public function — this is what stats_engine.py calls
# ---------------------------------------------------------------------------

def execute_restricted(code: str, df) -> dict:
    """
    Safely execute LLM-generated Pandas/NumPy code inside a sandbox.
    
    The code must assign its final result to a variable named 'result'.
    Example valid generated code:
        result = df['total_sales'].rolling(3).mean().tolist()
    
    Args:
        code: Python code string generated by the LLM
        df:   Pandas DataFrame — the user's uploaded financial data
    
    Returns:
        dict with keys:
            success (bool)
            result  (Any)  — the value of 'result' variable after execution
            error   (str)  — error message if failed, else None
    """
    import numpy as np
    import pandas as pd
    
    # Import scipy safely — it's optional (graceful if not installed)
    try:
        from scipy import stats as scipy_stats
    except ImportError:
        scipy_stats = None
        logger.warning("scipy not available — forecasting features limited")

    # --- Step 1: Compile with RestrictedPython ---
    # compile_restricted() checks the code for dangerous constructs
    # BEFORE any execution happens. If it finds "import os" — it raises.
    try:
        byte_code = compile_restricted(code, filename='<stats_code>', mode='exec')
    except SyntaxError as e:
        logger.error("RestrictedPython compile error: %s", e)
        return {
            'success': False,
            'result': None,
            'error': f"Code syntax error: {str(e)}"
        }
    except Exception as e:
        logger.error("RestrictedPython compile failed: %s", e)
        return {
            'success': False,
            'result': None,
            'error': f"Code compile failed: {str(e)}"
        }

    # --- Step 2: Build the sandbox environment ---
    restricted_globals = _build_restricted_globals(df, np, pd, scipy_stats)
    local_vars = {}  # Code writes its output here

    # --- Step 3: Execute inside the sandbox ---
    try:
        exec(byte_code, restricted_globals, local_vars)  # noqa: S102
    except Exception as e:
        logger.error("Restricted execution error: %s", e)
        return {
            'success': False,
            'result': None,
            'error': f"Execution error: {str(e)}"
        }

    # --- Step 4: Extract the 'result' variable ---
    # LLM is instructed to always write output to a variable called 'result'
    if 'result' not in local_vars:
        return {
            'success': False,
            'result': None,
            'error': "Generated code did not assign a 'result' variable. "
                     "Code must end with: result = <your answer>"
        }

    return {
        'success': True,
        'result': local_vars['result'],
        'error': None
    }